##############################################################################
# Example UPS Configuration
##############################################################################

[ups_network]
driver = usbhid-ups
port = auto
desc = "Network Infrastructure UPS"

[ups_servers]
driver = usbhid-ups
port = auto
desc = "Server Infrastructure UPS"

[ups_workstations]
driver = usbhid-ups
port = auto
desc = "Office Workstations UPS"
