##############################################################################
# Network Infrastructure UPS
##############################################################################

[ups_network]
driver = usbhid-ups
port = /dev/ups_network
desc = "Network Infrastructure UPS"

##############################################################################
# Server Infrastructure UPS
##############################################################################

[ups_servers]
driver = usbhid-ups
port = /dev/ups_servers
desc = "Server Infrastructure UPS"

##############################################################################
# Office Workstations UPS
##############################################################################

[ups_workstations]
driver = usbhid-ups
port = /dev/ups_workstations
desc = "Office Workstations UPS"
