##############################################################################
# UPS Monitoring
##############################################################################

MONITOR ups_network@localhost 1 zabbix ChangeThisPassword primary

MINSUPPLIES 1

SHUTDOWNCMD "/sbin/shutdown -h now"

POWERDOWNFLAG /etc/killpower
