##############################################################################
# Network UPS Tools UserParameters
##############################################################################

UserParameter=ups.status[*],upsc $1 ups.status

UserParameter=ups.charge[*],upsc $1 battery.charge

UserParameter=ups.runtime[*],upsc $1 battery.runtime

UserParameter=ups.load[*],upsc $1 ups.load

UserParameter=ups.input[*],upsc $1 input.voltage

UserParameter=ups.output[*],upsc $1 output.voltage

UserParameter=ups.battery[*],upsc $1 battery.voltage

UserParameter=ups.temperature[*],upsc $1 ups.temperature

UserParameter=ups.model[*],upsc $1 device.model

UserParameter=ups.manufacturer[*],upsc $1 device.mfr

UserParameter=ups.driver[*],upsc $1 driver.name
